apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
spec:
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: 'asia-northeast1-docker.pkg.dev/*PROJECT_ID/discord-bot/image:*SHORT_SHA'
        env:
        - name: DISCORD_TOKEN
          value: '*DISCORD_TOKEN'
        - name: DISCORD_CHANNEL_ID
          value: '*DISCORD_CHANNEL_ID'
        - name: DROPBOX_ID
          value: '*DROPBOX_ID'
        - name: DROPBOX_SECRET
          value: '*DROPBOX_SECRET'
        - name: DROPBOX_REFRESH_TOKEN
          value: '*DROPBOX_REFRESH_TOKEN'
        ports:
        - containerPort: 3000

