version: '3.8'
services:
  app:
    image: node:18.12.0-alpine
    container_name: discord-bot-app
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - LANG = C.UTF-8
      - CHOKIDAR_USEPOLLING = true
    volumes:
      - ./:/app
    entrypoint:
      - ash
    command:
      - -c
      - |
        [ -d ./node_modules ] || npm ci
        apk --update add tzdata
        cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
        npx nodemon -L src/main.ts
