version: "3.8"
services:
  app:
    build:
      context: .
      target: deno
    container_name: discord-bot-app
    working_dir: /app
    ports:
      - "8000:8000"
    networks:
      - external
    environment:
      - NODE_ENV=local
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
    tty: true
    command:
      - ash
    # - -c
    # - |
    #   [ -d ./node_modules ] || npm ci
    #   npx nodemon src/main.ts

  db:
    image: mysql:8.0
    container_name: discord-bot-db
    ports:
      - 3306:3306
    networks:
      - external
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=local_pass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mysql-data:
    name: discord-bot-db-data

networks:
  external:
    name: discord-bot
    internal: false
