version: "3.8"
services:
  app:
    image: node:18.12.0
    container_name: discord-bot
    working_dir: /usr/src/app
    ports: 
    - '3000:3000'
    environment:
      CHOKIDAR_USEPOLLING: 1
    volumes:
      - ./:/usr/src/app
    command:
      bash -c "npm install &&
      npm run watch"
